---
name: "Render Liquid File"
description: "Renders a liquid file"
branding:
  icon: 'file-text'
  color: 'green'
inputs:
  extname:
    description: "used for layouts/includes"
    required: false
    default: ""
  root:
    description: "root files for `.render()` and `.parse()`"
    required: true
  layouts:
    description: 'layout files for `{% layout %}`'
  partials:
    description: 'partial files for `{% render %}`'
  file:
    description: "The name of the file to render"
    required: true
outputs:
  rendered-content:
    description: "The content of the rendered file"
runs:
  using: "node20"
  main: "dist/index.js"
